### ISSUE TITLE
RPC

### ISSUE THREAD

**Issue by seimonw** [intel/dps-for-iot#65]
On the [ROS forum](https://discourse.ros.org/t/non-dds-based-rmw-implementation/5890/5) you mentioned "Built-in support for RPC". I don't see anything obvious specifically supporting this in the code, please could you explain this point further?

**Comment by malsbat** [comment]
RPC can be implemented using publication [acknowledgements](https://intel.github.io/dps-for-iot/tutorials-hello-world.html#acknowledging).

**Comment by seimonw** [comment]
Thanks for clarifying.
